---
- name: Find the target-server and add it to the in-memory inventory
  hosts: undercloud
  remote_user: stack
  vars_files:
    - vars/scaleup.yml
  pre_tasks:
    - name: Ensure the local artifacts directory exists
      file:
        path: "{{ artifacts_directory }}"
        state: directory
      delegate_to: localhost
  roles:
    - openstack_get_server

- name: Create additional OpenStack VMs and add them to OpenShift
  hosts: target-server
  remote_user: cloud-user
  vars_files:
    - vars/scaleup.yml
  roles:
    - openshift_on_openstack_scale
