---
# Run the dynamic inventory to get the current app hosts.
- name: Running the dynamic inventory file to get the current app hosts
  shell: ". {{ openstack_rc }}; python {{ inventory_py }} | jq '.app.hosts|length'"
  register: output
  changed_when: false

# Get the number of nodes in the app.hosts group.
- name: Setting the current node count
  set_fact:
    current_node_count: "{{ output['sdtout'] }}"

# Exit if the node target is less than how many nodes that are already running.
- fail:
    msg: "The OpenShift node target {{ openshift_node_target }} is less than or equal to than the current node count {{ current_node_count }}"
  when: openshift_node_target | int <= current_node_count | int

#  Create the blocks for scaling.
- name: Creating begin and end blocks for scaling
  set_fact:
    blocks: "{{ blocks }} [{'begin': {{ item }}, 'end': {{ (item|int + block_size|int < openshift_node_target|int)|ternary(item|int + block_size|int - 1, openshift_node_target|int - 1) }} }]"
  with_sequence: "start={{ current_node_count }} end={{ openshift_node_target|int - 1 }} stride={{ block_size }}"

# Create a variable that sources the rc file and runs the ansible-playbook command.
- name: Creating a variable that sources the OpenStack rc file and runs the ansible-playbook command
  set_fact:
    ansible_playbook: ". {{ openstack_rc }}; ansible-playbook"

# Create a variable that sources the rc file, sets INV_NO_APP_NODES=true and runs the ansible-playbook command.
- name: Creating a variable that sources the OpenStack rc file, sets INV_NO_APP_NODES=true and runs the ansible-playbook command
  set_fact:
    ansible_playbook_scaleup: ". {{ openstack_rc }}; INV_NO_APP_NODES=true ansible-playbook"

# Create a variable that sources the rc file and runs the OpenStack client command.
- name: Creating a variable that sources the OpenStack rc file and runs the openstack client command
  set_fact:
    openstack: ". {{ openstack_rc }}; openstack"

- name: Get the DNS information
  include_tasks: dns.yml

# Scale up this block of nodes.
- name: Scale loop
  include_tasks: scaleup.yml
  with_items: "{{ blocks }}"
  loop_control:
    # The loop_var changes the varabile name from item to avoid name collisions.
    loop_var: block
