---
- hosts: Compute
  user: heat-admin
  become: yes
  tasks:
    - name: Unload the kvm_intel module
      shell: modprobe -r kvm_intel

    - name: Activate the nesting feature
      shell: modprobe kvm_intel nested=1

    - name: Permanently enable nested virt
      lineinfile:
        path: /etc/modprobe.d/kvm.conf
        regexp: '^#options kvm_intel nested=1'
        line: 'options kvm_intel nested=1'
        state: present
        backrefs: yes

    - name: Set cpu passthrough
      shell: |
         crudini --set /var/lib/config-data/puppet-generated/nova_libvirt/etc/nova/nova.conf libvirt cpu_mode host-passthrough

    - name: Restart nova containers
      shell: docker ps | grep nova | awk '{print $1}' | xargs docker restart
