---
- name: Tasks to download and create an inventory of physical servers
  hosts: openstack-server
  vars:
    # The cloud is the identifier for the allocation.
    cloud: "{{ lookup('env', 'CLOUD_TITLE') | default('cloud03', true) }}"
    # The name of the json file can be created from the cloud.
    json_file: "{{ lookup('env', 'JSON_FILE') | default(cloud ~ '_instackenv.json', true) }}"
    # The remote directory to store any scale-ci files.
    install_directory: "{{ ansible_user_dir }}/scale-ci"
    # The path to save the JSON file locally.
    instackenv_file: "{{ install_directory }}/{{ json_file }}"
    # The path of the new inventory file to create.
    new_inventory_file: "{{ install_directory }}/instackenv_inventory"
    # URL prefix of the server with the JSON inventory file.
    url: "{{ lookup('env', 'URL') | default('http://quads.scalelab.redhat.com/cloud', true) }}"
  tasks:
    # Ensure the remote install directory exists.
    - name: Creating the {{ install_directory }} directory on {{ inventory_hostname }}
      file:
        path: "{{ install_directory }}"
        state: directory
        mode: 0700

    # Get the url for the given cloud.
    - name: "Downloading the {{ json_file }} file from {{ url }}"
      get_url:
        url: "{{ url }}/{{ json_file }}"
        dest: "{{ playbook_dir }}/{{ json_file }}"
      delegate_to: localhost

    # Parse the JSON file into an Ansible variable.
    - name: Reading {{ instackenv_file }}
      set_fact:
        instackenv: "{{ lookup('file', playbook_dir ~ '/{{ json_file }}') | from_json }}"

    # Create the new inventory file if necessary.
    - name: Creating {{ new_inventory_file }} if necessary
      file:
        state: touch
        path: "{{ new_inventory_file }}"

    # Write each address (minus "mgmt-") to a new inventory file.
    - name: Appending each node address to {{ new_inventory_file }}
      lineinfile:
        path: "{{ new_inventory_file }}"
        # Remove the prefix and write the name to the new inventory file.
        # Example: "pm_addr": "mgmt-b03-h03-1029p.rdu.openstack.engineering.redhat.com"
        line: "{{ item['pm_addr'] | replace('mgmt-', '') }}"
        insertafter: EOF
      with_items: "{{ instackenv['nodes'] }}"

    # Print the number of nodes from the instackenv file.
    - name: Printing how many nodes are in {{ instackenv_file }}
      debug:
        msg: "Nodes: {{ instackenv['nodes'] | length }}"
